version:  '3.8'
services:
  php:
    image: alma-test-technique_php
    volumes:
      - './:/var/www'
    env_file:
      - .env

  nginx:
    image: alma-test-technique_nginx
    depends_on:
      - "php"
      - "react-watcher"
    volumes:
      - './infra/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './public/build:/usr/share/nginx/html/build'
    ports:
      - '80:80'

  react-watcher:
    build:
      dockerfile: './infra/nginx/Dockerfile'
      context: '.'
      target: app-builder
      cache_from:
        - "alma-test-technique_nginx"
    volumes:
      - './public/build:/app/public/build'
      - './assets:/app/assets'
    command:
      'yarn build --watch'